import * as React from 'react';
import { Container, Typography, Box } from '@mui/material';

export default function AboutPage() {
  return (
    <Container maxWidth="md" sx={{ py: 4, px: { xs: 2, sm: 3 }, overflowX: 'hidden' }}>
      <Box sx={{ mb: 3 }}>
        <Typography variant="h4" sx={{ fontWeight: 700, mb: 1, fontSize: { xs: '1.5rem', sm: '2rem' } }}>About</Typography>
        <Typography variant="body1" sx={{ color: 'text.secondary', wordBreak: 'break-word', overflowWrap: 'anywhere' }}>
          Pickhub helps you explore NFL picks generated by different personas and scoring heuristics.
        </Typography>
      </Box>
      <Typography variant="body1" sx={{ lineHeight: 1.7, wordBreak: 'break-word', overflowWrap: 'anywhere' }}>
        Browse weekly matchups, see persona picks, and track performance on the leaderboard. The app
        sources data from public endpoints and generates factbooks and picks stored under public data,
        so what you see in the UI reflects the latest generated outputs.
      </Typography>
    </Container>
  );
}


